pikamon:
  logging:
    level: debug
  bot:
    maximum-spawn-duration: 300s
    spawn-chance: 0.08
    max-pokemon-id: 807
  channel-cache:
    number-counters: 100
    max-cost: 100
    buffer-size: 64
