pikamon:
  bot:
    maximum-spawn-duration: 300s
    spawn-chance: 1.00
    max-pokemon-id: 1
  cache:
    channel:
      number-counters: 100
      max-cost: 100
      buffer-size: 64
  logging:
    level: debug
  store:
    type: sqlite
    sqlite:
      location: ./data/sqlite/pikamon.db
